char * stage3(int);
void stageprint ();
void textcolor (int);
void clear ();
void phase1move ();
void Setlife ();
void makeclearstring ();
int skill1();
int skill2();
int skill3();
void phase1();
void phase3 ();
void phase2();
char * end(int);
void colobject (void *);
void rawobject (void *);
char * Achivement (int);
void stage3gotoxy(int x, int y);